apiVersion: v1
kind: LimitRange
metadata:
  name: quota-example-limitrange
  namespace: quota-example
spec:
  limits:
    - type: Container
      max:
        cpu: 0.5
        memory: 521Mi
      min:
        cpu: 0.1
        memory: 128Mi
      default:
        cpu: 0.2
        memory: 128Mi
